name       : libxxf86dga
version    : 1.1.4
release    : 10
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXxf86dga-1.1.4.tar.gz : e6361620a15ceba666901ca8423e8be0c6ed0271a7088742009160349173766b
license    :
    - MIT
summary    : X11 Direct Graphics Access extension library
component  : xorg.library
description: |
    libXxf86dga provides the XFree86-DGA extension, which allows direct graphics
    access to a framebuffer-like region, and also allows relative mouse
    reporting, et al.  It is mainly used by games and emulators for games.
builddeps  :
    - pkgconfig(xf86dgaproto)
    - pkgconfig32(xext)
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
