name       : libxxf86dga
version    : 1.1.5
release    : 12
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXxf86dga-1.1.5.tar.gz : 715e2bf5caf6276f0858eb4b11a1aef1a26beeb40dce2942387339da395bef69
license    :
    - MIT
summary    : X11 Direct Graphics Access extension library
component  : xorg.library
description: |
    libXxf86dga provides the XFree86-DGA extension, which allows direct graphics
    access to a framebuffer-like region, and also allows relative mouse
    reporting, et al.  It is mainly used by games and emulators for games.
builddeps  :
    - pkgconfig(xf86dgaproto)
    - pkgconfig32(xext)
    - pkgconfig32(x11)
emul32     : yes
optimize   : speed
patterns   :
    - devel :
        - /usr/share/man
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
