name        : libxxf86dga
version     : 1.1.4
release     : 7
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libXxf86dga-1.1.4.tar.gz : e6361620a15ceba666901ca8423e8be0c6ed0271a7088742009160349173766b
license     :
    - MIT
summary     : X11 Direct Graphics Access extension library
component   : xorg.library
builddeps   :
    - pkgconfig(xf86dgaproto)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
optimize    : speed
patterns    :
    - devel:
        - /usr/share/man
description : |
    libXxf86dga provides the XFree86-DGA extension, which allows direct graphics access to a framebuffer-like region, and also allows relative mouse reporting, et al.  It is mainly used by games and emulators for games.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
